VHDL_SOURCES += $(PWD)/../../src/rtl/MuctpiDataTypes.vhd
VHDL_SOURCES += $(PWD)/../../src/rtl/MuctpiFunctions.vhd
VHDL_SOURCES += $(PWD)/../../src/rtl/SortingHierarchical.vhd
VHDL_SOURCES += $(PWD)/../../src/rtl/mh_compare_pt.vhd
VHDL_SOURCES += $(PWD)/../../src/rtl/mh_multiplexor.vhd
VHDL_SOURCES += $(PWD)/../../src/rtl/muon_sorter_hierarchical.vhd
VHDL_SOURCES += $(PWD)/../../src/rtl/muon_sorter.vhd

