#*****************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# wrapper.tcl: Tcl script for re-creating project 'wrapper'
#
# Generated by Vivado on Fri Dec 07 17:19:05 +0100 2018
# IP Build 2256618 on Thu Jun 14 22:10:49 MDT 2018
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (wrapper.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "D:/mygitlab/sorting/src/rtl/lfsr.sv"
#    "D:/mygitlab/sorting/src/rtl/reducer.sv"
#    "D:/mygitlab/sorting/src/rtl/MuctpiDataTypes.vhd"
#    "D:/mygitlab/sorting/src/rtl/MuctpiFunctions.vhd"
#    "D:/mygitlab/sorting/src/rtl/muon_sorter.vhd"
#    "D:/mygitlab/sorting/src/rtl/wrapper.vhd"
#    "D:/mygitlab/sorting/src/xdc/wrapper.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "wrapper"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "wrapper.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/wrapper"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xcvu9p-flgc2104-2-e

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
set_property -name "dsa.emu_dir" -value "emu" -objects $obj
set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
set_property -name "dsa.flash_size" -value "1024" -objects $obj
set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
set_property -name "dsa.host_interface" -value "pcie" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
set_property -name "dsa.uses_pr" -value "1" -objects $obj
set_property -name "dsa.vendor" -value "xilinx" -objects $obj
set_property -name "dsa.version" -value "0.0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../src/rtl/lfsr.sv"] \
 [file normalize "${origin_dir}/../src/rtl/reducer.sv"] \
 [file normalize "${origin_dir}/../src/rtl/MuctpiDataTypes.vhd"] \
 [file normalize "${origin_dir}/../src/rtl/MuctpiFunctions.vhd"] \
 [file normalize "${origin_dir}/../src/rtl/muon_sorter.vhd"] \
 [file normalize "${origin_dir}/../src/rtl/wrapper.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../src/rtl/lfsr.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../src/rtl/reducer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../src/rtl/MuctpiDataTypes.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../src/rtl/MuctpiFunctions.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../src/rtl/muon_sorter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../src/rtl/wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../src/xdc/wrapper.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/../src/xdc/wrapper.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/../src/xdc/wrapper.xdc"]" -objects $obj
set_property -name "target_part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "target_ucf" -value "[file normalize "$origin_dir/../src/xdc/wrapper.xdc"]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2018" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# Create 'N2O2' run (if not found)
if {[string equal [get_runs -quiet N2O2] ""]} {
    create_run -name N2O2 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N2O2]
  set_property flow "Vivado Synthesis 2018" [get_runs N2O2]
}
set obj [get_runs N2O2]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N2O2_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N2O2] N2O2_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N2O2_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N2O2
}
set obj [get_report_configs -of_objects [get_runs N2O2] N2O2_synth_report_utilization_0]
if { $obj != "" } {

}
# Create 'N=2_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N2O2] N=2_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N=2_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N2O2
}
set obj [get_report_configs -of_objects [get_runs N2O2] N=2_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N2O2]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=2 -generic O=2" -objects $obj

# Create 'N3O3' run (if not found)
if {[string equal [get_runs -quiet N3O3] ""]} {
    create_run -name N3O3 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N3O3]
  set_property flow "Vivado Synthesis 2018" [get_runs N3O3]
}
set obj [get_runs N3O3]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N3O3_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N3O3] N3O3_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N3O3_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N3O3
}
set obj [get_report_configs -of_objects [get_runs N3O3] N3O3_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N3O3]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=3 -generic O=3" -objects $obj

# Create 'N4O4' run (if not found)
if {[string equal [get_runs -quiet N4O4] ""]} {
    create_run -name N4O4 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N4O4]
  set_property flow "Vivado Synthesis 2018" [get_runs N4O4]
}
set obj [get_runs N4O4]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N4O4_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N4O4] N4O4_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N4O4_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N4O4
}
set obj [get_report_configs -of_objects [get_runs N4O4] N4O4_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N4O4]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=4 -generic O=4" -objects $obj

# Create 'N5O5' run (if not found)
if {[string equal [get_runs -quiet N5O5] ""]} {
    create_run -name N5O5 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N5O5]
  set_property flow "Vivado Synthesis 2018" [get_runs N5O5]
}
set obj [get_runs N5O5]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N5O5_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N5O5] N5O5_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N5O5_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N5O5
}
set obj [get_report_configs -of_objects [get_runs N5O5] N5O5_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N5O5]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=5 -generic O=5" -objects $obj

# Create 'N6O6' run (if not found)
if {[string equal [get_runs -quiet N6O6] ""]} {
    create_run -name N6O6 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N6O6]
  set_property flow "Vivado Synthesis 2018" [get_runs N6O6]
}
set obj [get_runs N6O6]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N6O6_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N6O6] N6O6_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N6O6_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N6O6
}
set obj [get_report_configs -of_objects [get_runs N6O6] N6O6_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N6O6]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=6 -generic O=6" -objects $obj

# Create 'N7O7' run (if not found)
if {[string equal [get_runs -quiet N7O7] ""]} {
    create_run -name N7O7 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N7O7]
  set_property flow "Vivado Synthesis 2018" [get_runs N7O7]
}
set obj [get_runs N7O7]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N7O7_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N7O7] N7O7_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N7O7_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N7O7
}
set obj [get_report_configs -of_objects [get_runs N7O7] N7O7_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N7O7]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=7 -generic O=7" -objects $obj

# Create 'N8O8' run (if not found)
if {[string equal [get_runs -quiet N8O8] ""]} {
    create_run -name N8O8 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N8O8]
  set_property flow "Vivado Synthesis 2018" [get_runs N8O8]
}
set obj [get_runs N8O8]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N8O8_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N8O8] N8O8_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N8O8_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N8O8
}
set obj [get_report_configs -of_objects [get_runs N8O8] N8O8_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N8O8]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=8 -generic O=8" -objects $obj

# Create 'N9O9' run (if not found)
if {[string equal [get_runs -quiet N9O9] ""]} {
    create_run -name N9O9 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N9O9]
  set_property flow "Vivado Synthesis 2018" [get_runs N9O9]
}
set obj [get_runs N9O9]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N9O9_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N9O9] N9O9_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N9O9_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N9O9
}
set obj [get_report_configs -of_objects [get_runs N9O9] N9O9_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N9O9]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=9 -generic O=9" -objects $obj

# Create 'N10O10' run (if not found)
if {[string equal [get_runs -quiet N10O10] ""]} {
    create_run -name N10O10 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N10O10]
  set_property flow "Vivado Synthesis 2018" [get_runs N10O10]
}
set obj [get_runs N10O10]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N10O10_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N10O10] N10O10_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N10O10_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N10O10
}
set obj [get_report_configs -of_objects [get_runs N10O10] N10O10_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N10O10]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=10 -generic O=10" -objects $obj

# Create 'N11O11' run (if not found)
if {[string equal [get_runs -quiet N11O11] ""]} {
    create_run -name N11O11 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N11O11]
  set_property flow "Vivado Synthesis 2018" [get_runs N11O11]
}
set obj [get_runs N11O11]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N11O11_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N11O11] N11O11_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N11O11_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N11O11
}
set obj [get_report_configs -of_objects [get_runs N11O11] N11O11_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N11O11]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=11 -generic O=11" -objects $obj

# Create 'N12O12' run (if not found)
if {[string equal [get_runs -quiet N12O12] ""]} {
    create_run -name N12O12 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N12O12]
  set_property flow "Vivado Synthesis 2018" [get_runs N12O12]
}
set obj [get_runs N12O12]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N12O12_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N12O12] N12O12_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N12O12_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N12O12
}
set obj [get_report_configs -of_objects [get_runs N12O12] N12O12_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N12O12]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=12 -generic O=12" -objects $obj

# Create 'N13O13' run (if not found)
if {[string equal [get_runs -quiet N13O13] ""]} {
    create_run -name N13O13 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N13O13]
  set_property flow "Vivado Synthesis 2018" [get_runs N13O13]
}
set obj [get_runs N13O13]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N13O13_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N13O13] N13O13_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N13O13_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N13O13
}
set obj [get_report_configs -of_objects [get_runs N13O13] N13O13_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N13O13]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=13 -generic O=13" -objects $obj

# Create 'N14O14' run (if not found)
if {[string equal [get_runs -quiet N14O14] ""]} {
    create_run -name N14O14 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N14O14]
  set_property flow "Vivado Synthesis 2018" [get_runs N14O14]
}
set obj [get_runs N14O14]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N14O14_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N14O14] N14O14_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N14O14_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N14O14
}
set obj [get_report_configs -of_objects [get_runs N14O14] N14O14_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N14O14]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=14 -generic O=14" -objects $obj

# Create 'N15O15' run (if not found)
if {[string equal [get_runs -quiet N15O15] ""]} {
    create_run -name N15O15 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N15O15]
  set_property flow "Vivado Synthesis 2018" [get_runs N15O15]
}
set obj [get_runs N15O15]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N15O15_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N15O15] N15O15_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N15O15_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N15O15
}
set obj [get_report_configs -of_objects [get_runs N15O15] N15O15_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N15O15]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=15 -generic O=15" -objects $obj

# Create 'N16O16' run (if not found)
if {[string equal [get_runs -quiet N16O16] ""]} {
    create_run -name N16O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N16O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N16O16]
}
set obj [get_runs N16O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N16O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N16O16] N16O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N16O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N16O16
}
set obj [get_report_configs -of_objects [get_runs N16O16] N16O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N16O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=16 -generic O=16" -objects $obj

# Create 'N17O16' run (if not found)
if {[string equal [get_runs -quiet N17O16] ""]} {
    create_run -name N17O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N17O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N17O16]
}
set obj [get_runs N17O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N17O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N17O16] N17O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N17O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N17O16
}
set obj [get_report_configs -of_objects [get_runs N17O16] N17O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N17O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=17 -generic O=16" -objects $obj

# Create 'N18O16' run (if not found)
if {[string equal [get_runs -quiet N18O16] ""]} {
    create_run -name N18O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N18O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N18O16]
}
set obj [get_runs N18O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N18O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N18O16] N18O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N18O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N18O16
}
set obj [get_report_configs -of_objects [get_runs N18O16] N18O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N18O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=18 -generic O=16" -objects $obj

# Create 'N19O16' run (if not found)
if {[string equal [get_runs -quiet N19O16] ""]} {
    create_run -name N19O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N19O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N19O16]
}
set obj [get_runs N19O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N19O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N19O16] N19O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N19O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N19O16
}
set obj [get_report_configs -of_objects [get_runs N19O16] N19O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N19O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=19 -generic O=16" -objects $obj

# Create 'N20O16' run (if not found)
if {[string equal [get_runs -quiet N20O16] ""]} {
    create_run -name N20O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N20O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N20O16]
}
set obj [get_runs N20O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N20O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N20O16] N20O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N20O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N20O16
}
set obj [get_report_configs -of_objects [get_runs N20O16] N20O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N20O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=20 -generic O=16" -objects $obj

# Create 'N21O16' run (if not found)
if {[string equal [get_runs -quiet N21O16] ""]} {
    create_run -name N21O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N21O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N21O16]
}
set obj [get_runs N21O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N21O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N21O16] N21O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N21O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N21O16
}
set obj [get_report_configs -of_objects [get_runs N21O16] N21O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N21O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=21 -generic O=16" -objects $obj

# Create 'N22O16' run (if not found)
if {[string equal [get_runs -quiet N22O16] ""]} {
    create_run -name N22O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N22O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N22O16]
}
set obj [get_runs N22O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N22O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N22O16] N22O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N22O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N22O16
}
set obj [get_report_configs -of_objects [get_runs N22O16] N22O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N22O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=22 -generic O=16" -objects $obj

# Create 'N23O16' run (if not found)
if {[string equal [get_runs -quiet N23O16] ""]} {
    create_run -name N23O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N23O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N23O16]
}
set obj [get_runs N23O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N23O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N23O16] N23O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N23O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N23O16
}
set obj [get_report_configs -of_objects [get_runs N23O16] N23O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N23O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=23 -generic O=16" -objects $obj

# Create 'N24O16' run (if not found)
if {[string equal [get_runs -quiet N24O16] ""]} {
    create_run -name N24O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N24O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N24O16]
}
set obj [get_runs N24O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N24O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N24O16] N24O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N24O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N24O16
}
set obj [get_report_configs -of_objects [get_runs N24O16] N24O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N24O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=24 -generic O=16" -objects $obj

# Create 'N25O16' run (if not found)
if {[string equal [get_runs -quiet N25O16] ""]} {
    create_run -name N25O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N25O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N25O16]
}
set obj [get_runs N25O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N25O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N25O16] N25O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N25O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N25O16
}
set obj [get_report_configs -of_objects [get_runs N25O16] N25O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N25O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=25 -generic O=16" -objects $obj

# Create 'N26O16' run (if not found)
if {[string equal [get_runs -quiet N26O16] ""]} {
    create_run -name N26O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N26O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N26O16]
}
set obj [get_runs N26O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N26O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N26O16] N26O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N26O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N26O16
}
set obj [get_report_configs -of_objects [get_runs N26O16] N26O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N26O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=26 -generic O=16" -objects $obj

# Create 'N27O16' run (if not found)
if {[string equal [get_runs -quiet N27O16] ""]} {
    create_run -name N27O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N27O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N27O16]
}
set obj [get_runs N27O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N27O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N27O16] N27O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N27O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N27O16
}
set obj [get_report_configs -of_objects [get_runs N27O16] N27O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N27O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=27 -generic O=16" -objects $obj

# Create 'N28O16' run (if not found)
if {[string equal [get_runs -quiet N28O16] ""]} {
    create_run -name N28O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N28O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N28O16]
}
set obj [get_runs N28O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N28O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N28O16] N28O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N28O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N28O16
}
set obj [get_report_configs -of_objects [get_runs N28O16] N28O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N28O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=28 -generic O=16" -objects $obj

# Create 'N29O16' run (if not found)
if {[string equal [get_runs -quiet N29O16] ""]} {
    create_run -name N29O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N29O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N29O16]
}
set obj [get_runs N29O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N29O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N29O16] N29O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N29O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N29O16
}
set obj [get_report_configs -of_objects [get_runs N29O16] N29O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N29O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=29 -generic O=16" -objects $obj

# Create 'N30O16' run (if not found)
if {[string equal [get_runs -quiet N30O16] ""]} {
    create_run -name N30O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N30O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N30O16]
}
set obj [get_runs N30O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N30O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N30O16] N30O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N30O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N30O16
}
set obj [get_report_configs -of_objects [get_runs N30O16] N30O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N30O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=30 -generic O=16" -objects $obj

# Create 'N31O16' run (if not found)
if {[string equal [get_runs -quiet N31O16] ""]} {
    create_run -name N31O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N31O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N31O16]
}
set obj [get_runs N31O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N31O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N31O16] N31O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N31O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N31O16
}
set obj [get_report_configs -of_objects [get_runs N31O16] N31O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N31O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=31 -generic O=16" -objects $obj

# Create 'N32O16' run (if not found)
if {[string equal [get_runs -quiet N32O16] ""]} {
    create_run -name N32O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N32O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N32O16]
}
set obj [get_runs N32O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N32O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N32O16] N32O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N32O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N32O16
}
set obj [get_report_configs -of_objects [get_runs N32O16] N32O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N32O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=32 -generic O=16" -objects $obj

# Create 'N33O16' run (if not found)
if {[string equal [get_runs -quiet N33O16] ""]} {
    create_run -name N33O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N33O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N33O16]
}
set obj [get_runs N33O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N33O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N33O16] N33O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N33O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N33O16
}
set obj [get_report_configs -of_objects [get_runs N33O16] N33O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N33O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=33 -generic O=16" -objects $obj

# Create 'N34O16' run (if not found)
if {[string equal [get_runs -quiet N34O16] ""]} {
    create_run -name N34O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N34O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N34O16]
}
set obj [get_runs N34O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N34O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N34O16] N34O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N34O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N34O16
}
set obj [get_report_configs -of_objects [get_runs N34O16] N34O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N34O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=34 -generic O=16" -objects $obj

# Create 'N35O16' run (if not found)
if {[string equal [get_runs -quiet N35O16] ""]} {
    create_run -name N35O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N35O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N35O16]
}
set obj [get_runs N35O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N35O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N35O16] N35O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N35O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N35O16
}
set obj [get_report_configs -of_objects [get_runs N35O16] N35O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N35O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=35 -generic O=16" -objects $obj

# Create 'N36O16' run (if not found)
if {[string equal [get_runs -quiet N36O16] ""]} {
    create_run -name N36O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N36O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N36O16]
}
set obj [get_runs N36O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N36O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N36O16] N36O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N36O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N36O16
}
set obj [get_report_configs -of_objects [get_runs N36O16] N36O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N36O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=36 -generic O=16" -objects $obj

# Create 'N37O16' run (if not found)
if {[string equal [get_runs -quiet N37O16] ""]} {
    create_run -name N37O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N37O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N37O16]
}
set obj [get_runs N37O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N37O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N37O16] N37O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N37O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N37O16
}
set obj [get_report_configs -of_objects [get_runs N37O16] N37O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N37O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=37 -generic O=16" -objects $obj

# Create 'N38O16' run (if not found)
if {[string equal [get_runs -quiet N38O16] ""]} {
    create_run -name N38O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N38O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N38O16]
}
set obj [get_runs N38O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N38O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N38O16] N38O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N38O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N38O16
}
set obj [get_report_configs -of_objects [get_runs N38O16] N38O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N38O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=38 -generic O=16" -objects $obj

# Create 'N39O16' run (if not found)
if {[string equal [get_runs -quiet N39O16] ""]} {
    create_run -name N39O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N39O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N39O16]
}
set obj [get_runs N39O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N39O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N39O16] N39O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N39O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N39O16
}
set obj [get_report_configs -of_objects [get_runs N39O16] N39O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N39O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=39 -generic O=16" -objects $obj

# Create 'N40O16' run (if not found)
if {[string equal [get_runs -quiet N40O16] ""]} {
    create_run -name N40O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N40O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N40O16]
}
set obj [get_runs N40O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N40O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N40O16] N40O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N40O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N40O16
}
set obj [get_report_configs -of_objects [get_runs N40O16] N40O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N40O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=40 -generic O=16" -objects $obj

# Create 'N41O16' run (if not found)
if {[string equal [get_runs -quiet N41O16] ""]} {
    create_run -name N41O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N41O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N41O16]
}
set obj [get_runs N41O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N41O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N41O16] N41O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N41O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N41O16
}
set obj [get_report_configs -of_objects [get_runs N41O16] N41O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N41O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=41 -generic O=16" -objects $obj

# Create 'N42O16' run (if not found)
if {[string equal [get_runs -quiet N42O16] ""]} {
    create_run -name N42O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N42O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N42O16]
}
set obj [get_runs N42O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N42O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N42O16] N42O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N42O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N42O16
}
set obj [get_report_configs -of_objects [get_runs N42O16] N42O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N42O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=42 -generic O=16" -objects $obj

# Create 'N43O16' run (if not found)
if {[string equal [get_runs -quiet N43O16] ""]} {
    create_run -name N43O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N43O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N43O16]
}
set obj [get_runs N43O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N43O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N43O16] N43O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N43O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N43O16
}
set obj [get_report_configs -of_objects [get_runs N43O16] N43O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N43O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=43 -generic O=16" -objects $obj

# Create 'N44O16' run (if not found)
if {[string equal [get_runs -quiet N44O16] ""]} {
    create_run -name N44O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N44O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N44O16]
}
set obj [get_runs N44O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N44O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N44O16] N44O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N44O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N44O16
}
set obj [get_report_configs -of_objects [get_runs N44O16] N44O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N44O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=44 -generic O=16" -objects $obj

# Create 'N45O16' run (if not found)
if {[string equal [get_runs -quiet N45O16] ""]} {
    create_run -name N45O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N45O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N45O16]
}
set obj [get_runs N45O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N45O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N45O16] N45O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N45O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N45O16
}
set obj [get_report_configs -of_objects [get_runs N45O16] N45O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N45O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=45 -generic O=16" -objects $obj

# Create 'N46O16' run (if not found)
if {[string equal [get_runs -quiet N46O16] ""]} {
    create_run -name N46O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N46O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N46O16]
}
set obj [get_runs N46O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N46O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N46O16] N46O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N46O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N46O16
}
set obj [get_report_configs -of_objects [get_runs N46O16] N46O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N46O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=46 -generic O=16" -objects $obj

# Create 'N47O16' run (if not found)
if {[string equal [get_runs -quiet N47O16] ""]} {
    create_run -name N47O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N47O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N47O16]
}
set obj [get_runs N47O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N47O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N47O16] N47O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N47O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N47O16
}
set obj [get_report_configs -of_objects [get_runs N47O16] N47O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N47O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=47 -generic O=16" -objects $obj

# Create 'N48O16' run (if not found)
if {[string equal [get_runs -quiet N48O16] ""]} {
    create_run -name N48O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N48O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N48O16]
}
set obj [get_runs N48O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N48O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N48O16] N48O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N48O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N48O16
}
set obj [get_report_configs -of_objects [get_runs N48O16] N48O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N48O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=48 -generic O=16" -objects $obj

# Create 'N49O16' run (if not found)
if {[string equal [get_runs -quiet N49O16] ""]} {
    create_run -name N49O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N49O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N49O16]
}
set obj [get_runs N49O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N49O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N49O16] N49O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N49O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N49O16
}
set obj [get_report_configs -of_objects [get_runs N49O16] N49O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N49O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=49 -generic O=16" -objects $obj

# Create 'N50O16' run (if not found)
if {[string equal [get_runs -quiet N50O16] ""]} {
    create_run -name N50O16 -part xcvu9p-flgc2104-2-e -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs N50O16]
  set_property flow "Vivado Synthesis 2018" [get_runs N50O16]
}
set obj [get_runs N50O16]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Utilization} $obj
set_property set_report_strategy_name 0 $obj
# Create 'N50O16_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs N50O16] N50O16_synth_report_utilization_0] "" ] } {
  create_report_config -report_name N50O16_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs N50O16
}
set obj [get_report_configs -of_objects [get_runs N50O16] N50O16_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs N50O16]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj
set_property -name "steps.synth_design.args.more options" -value "-generic N=50 -generic O=16" -objects $obj

# set the current synth run
current_run -synthesis [get_runs N17O16]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xcvu9p-flgc2104-2-e -flow {Vivado Implementation 2018} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2018" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {

}
set obj [get_runs impl_1]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# Create 'impl_2' run (if not found)
if {[string equal [get_runs -quiet impl_2] ""]} {
    create_run -name impl_2 -part xcvu9p-flgc2104-2-e -flow {Vivado Implementation 2018} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run N17O16
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_2]
  set_property flow "Vivado Implementation 2018" [get_runs impl_2]
}
set obj [get_runs impl_2]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_2_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_2_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_2_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_io_0] "" ] } {
  create_report_config -report_name impl_2_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_2_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_2_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_2_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_2_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'impl_2_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_2_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_2_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_2_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_2_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_power_0] "" ] } {
  create_report_config -report_name impl_2_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_2_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_2_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_2_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_2_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_bus_skew_0]
if { $obj != "" } {

}
# Create 'impl_2_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_2_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_2_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {

}
set obj [get_runs impl_2]
set_property -name "part" -value "xcvu9p-flgc2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_2]

puts "INFO: Project created:${_xil_proj_name_}"
